In [86]:
import numpy as np
import pandas as pd
from math import *

In [87]:
# n equal to number of features
n = 5

# m equal to number of samples
m = 100

In [88]:
# Coefficients of each feature


In [89]:
class RecommendationSystem:
    
    def __init__(self, features):
        self.features = features

        
    def recommend(self, values, customer_feature1, customer_feature2, customer_feature3, customer_feature4, k1 = 4, k2=1, k3=1, k4=1):
    
        #k nearest neighbor
        k_indices1 = self.__oneRecommend(customer_feature1, values, k1)
        k_indices2 = self.__oneRecommend(customer_feature2, values, k2)
        k_indices3 = self.__oneRecommend(customer_feature3, values, k3)
        k_indices4 = self.__oneRecommend(customer_feature4, values, k4)
                
        # merge and unigue indices(union)
        k_indices = np.append(k_indices1, np.append(k_indices2, np.append(k_indices3, k_indices4)))
        
        # return the selected style indices 
        return k_indices


    def __oneRecommend(self, customer, values, k):
        # compute distances by one of the distance(distance_1, distance_2, ...) functions
        distances = np.array([self.__distance_2(customer, f, values) for f in self.features])
        
        # return k nearest style indices
        return np.argsort(distances)[:k]


    def recommend2(self, features, values, k):
        
        distance = np.array([self.distance_2(features, f, values) for f in self.features])
        k_indeces1 = np.argsort(distance)[:k]
        return k_indeces1
    
    

    def __distance_1(self, customer, clothes, values):
        lowestMines = self.__lowestMines(customer, clothes)      
        return np.sum(values * np.abs(lowestMines))
    
    
    def __distance_2(self, customer, clothes, values):
        lowestMines = self.__lowestMines(customer, clothes)      
        return np.sqrt(np.sum(values*((lowestMines) ** 2 )))


    def __lowestMines(self, customer, clothes):
        bestClothes = []
        tmpArray1 = []
        for i in range(len(customer)):
            for j in range(np.shape(clothes)[1]):
                tmpArray1.append(abs((customer[i] - clothes[i][j])))
            bestClothes.append(min(tmpArray1))  
            tmpArray1 = []
        return np.array(bestClothes) 
        

    
    

# creating random data and check the answers...


In [90]:
import random 

In [91]:
#create random clothes tags
my_list = [0, 1, 2, 3, 4]
clothes = np.zeros((m, n, 3))
for i in range(m):
    for j in range(n):
        for k in range(3):
            clothes[i, j, k] = random.choice(my_list)
    
print(clothes[:2])

[[[2. 3. 1.]
  [4. 0. 4.]
  [4. 1. 1.]
  [3. 2. 1.]
  [0. 4. 4.]]

 [[4. 3. 0.]
  [1. 2. 0.]
  [0. 2. 0.]
  [1. 4. 3.]
  [1. 4. 2.]]]


In [92]:
#create random personal tags
customer1 = np.array([random.choice(my_list) for j in range(n)])

#create 3 random selected style tags
customer2 = np.array([random.choice(my_list) for j in range(n)])
customer3 = np.array([random.choice(my_list) for j in range(n)])
customer4 = np.array([random.choice(my_list) for j in range(n)])
print(customer1, customer2, customer3, customer4)

[3 4 1 3 0] [3 2 4 4 4] [2 1 3 1 3] [1 4 1 3 3]


In [93]:
similarity = RecommendationSystem(clothes)

distances_indices = similarity.recommend([1,1,1,1,1], customer1, customer2, customer3, customer4)

In [94]:
print(customer1)
print(clothes[distances_indices])
type(distances_indices)

[3 4 1 3 0]
[[[2. 3. 1.]
  [4. 0. 4.]
  [4. 1. 1.]
  [3. 2. 1.]
  [0. 4. 4.]]

 [[0. 0. 3.]
  [4. 0. 2.]
  [3. 1. 1.]
  [1. 4. 3.]
  [4. 2. 0.]]

 [[2. 0. 3.]
  [3. 3. 4.]
  [1. 1. 2.]
  [2. 0. 3.]
  [2. 0. 4.]]

 [[0. 3. 3.]
  [4. 1. 2.]
  [2. 3. 1.]
  [1. 0. 3.]
  [0. 1. 4.]]

 [[0. 3. 1.]
  [2. 0. 4.]
  [4. 1. 3.]
  [2. 4. 4.]
  [0. 4. 3.]]

 [[0. 3. 2.]
  [2. 1. 2.]
  [3. 3. 2.]
  [1. 2. 1.]
  [3. 3. 1.]]

 [[1. 0. 1.]
  [4. 1. 1.]
  [0. 1. 0.]
  [0. 0. 3.]
  [0. 3. 0.]]]


numpy.ndarray