In [1]:
import numpy as np
import pandas as pd
from math import *

In [2]:
# n equal to number of features
n = 8

# m equal to number of samples
m = 100

In [3]:
# Coefficients of each feature
values = [1, 0.6, 1, 1, 0.5, 0.75, 0.80, 1]


In [4]:
class Similarity:
    
    def __init__(self, features, values):
        self.features = features
        self.values = values
    
        
    def recommend(self, customer_features, k = 15):
        # compute distances by one of the distance(distance_1, distance_2, ...) functions
        distances = np.array([self.distance_2(customer_features, f) for f in self.features])
        
        # get k nearest style indices
        k_indices = np.argsort(distances)[:k]
        
        #print(distances[k_indices])

        # return the selected style indices
        return k_indices
    

    def distance_1(self, x, y):
        return np.sum(self.values * np.abs(x - y))
    
    
    def distance_2(self, x, y):
        return np.sqrt(np.sum(self.values * ((x - y) ** 2))) 
    
    

# creating random data and check the answers...


In [5]:
import random 

In [6]:
#create random clothes tags
my_list = [0, 1, 2, 3, 4]
clothes = np.zeros((100, 8))

for i in range(100):
    clothes[i] = ([random.choice(my_list) for j in range(n)])
    
print(clothes[:3])

[[2. 4. 3. 2. 3. 2. 2. 2.]
 [1. 1. 3. 3. 4. 2. 3. 1.]
 [3. 4. 4. 0. 4. 3. 1. 2.]]


In [7]:
#create random person tags
customer = np.array([random.choice(my_list) for j in range(n)])

print(customer)

[3 4 2 3 1 4 4 0]


In [8]:
similarity = Similarity(clothes, values)

distances_indices = similarity.recommend(customer)

In [9]:
print(clothes[distances_indices])

[[4. 4. 0. 2. 1. 4. 4. 1.]
 [2. 2. 3. 3. 2. 3. 2. 0.]
 [3. 0. 2. 3. 0. 3. 3. 1.]
 [3. 3. 2. 3. 1. 3. 2. 3.]
 [1. 2. 2. 3. 3. 3. 3. 2.]
 [4. 3. 0. 2. 1. 1. 3. 0.]
 [2. 3. 0. 2. 0. 2. 2. 1.]
 [2. 4. 2. 4. 4. 3. 1. 0.]
 [3. 4. 1. 2. 0. 4. 2. 3.]
 [1. 2. 0. 3. 0. 4. 4. 2.]
 [2. 2. 0. 2. 3. 2. 3. 1.]
 [1. 4. 0. 2. 1. 2. 2. 0.]
 [2. 4. 3. 2. 3. 2. 2. 2.]
 [0. 4. 4. 2. 0. 4. 3. 0.]
 [2. 2. 0. 2. 1. 4. 1. 0.]]
