In [1]:
import numpy as np
import pandas as pd
from math import *

In [2]:
# n equal to number of features
n = 5

# m equal to number of samples
m = 100

In [3]:
# Coefficients of each feature
values = [1, 1, 1, 1, 1]


In [4]:
class Similarity:
    
    def __init__(self, features):
        self.features = features

        
    def recommend(self, values, customer_feature1, customer_feature2, customer_feature3, customer_feature4, k1 = 6, k2=2, k3=2, k4=2):
        # compute distances by one of the distance(distance_1, distance_2, ...) functions
        distances1 = np.array([self.distance_2(customer_feature1, f, values) for f in self.features])
        distances2 = np.array([self.distance_2(customer_feature2, f, values) for f in self.features])
        distances3 = np.array([self.distance_2(customer_feature3, f, values) for f in self.features])
        distances4 = np.array([self.distance_2(customer_feature4, f, values) for f in self.features])

        # get k nearest style indices
        k_indices1 = np.argsort(distances1)[:k1]
        k_indices2 = np.argsort(distances2)[:k2]
        k_indices3 = np.argsort(distances3)[:k3]
        k_indices4 = np.argsort(distances4)[:k4]

        #print(distances1[k_indices1])
        #print(self.features[k_indices1])
        
        # merge and unigue indices(union)
        k_indices = np.union1d(k_indices1, np.union1d(k_indices2, np.union1d(k_indices3, k_indices4)))
        #print(self.features[k_indices])
        
        # return the selected style indices
        return k_indices
    

    def distance_1(self, x, y, values):
        return np.sum(values * np.abs(x - y))
    
    
    def distance_2(self, x, y, values):
        return np.sqrt(np.sum(values * ((x - y) ** 2))) 
    
    

# creating random data and check the answers...


In [5]:
import random 

In [6]:
#create random clothes tags
my_list = [0, 1, 2, 3, 4]
clothes = np.zeros((100, n))

for i in range(100):
    clothes[i] = ([random.choice(my_list) for j in range(n)])
    
print(clothes[:3])

[[4. 4. 4. 1. 4.]
 [3. 2. 3. 0. 0.]
 [4. 3. 4. 1. 4.]]


In [8]:
#create random personal tags
customer1 = np.array([random.choice(my_list) for j in range(n)])

#create 3 random selected style tags
customer2 = np.array([random.choice(my_list) for j in range(n)])
customer3 = np.array([random.choice(my_list) for j in range(n)])
customer4 = np.array([random.choice(my_list) for j in range(n)])
print(customer1, customer2, customer3, customer4)

[1 3 2 2 0] [4 4 0 4 1] [4 4 0 1 4] [0 2 4 4 4]


In [9]:
similarity = Similarity(clothes)

distances_indices = similarity.recommend(values, customer1, customer2, customer3, customer4, k1= 3, k2=1, k3=1, k4=1)

In [10]:
print(clothes[distances_indices])

[[4. 3. 0. 4. 2.]
 [1. 3. 0. 2. 0.]
 [2. 3. 2. 3. 0.]
 [4. 4. 1. 2. 4.]
 [1. 4. 2. 3. 2.]
 [0. 2. 4. 4. 2.]]
