In [966]:
import numpy as np
import pandas as pd
from math import *
import math

In [967]:
# n equal to number of features
n = 5

# m equal to number of samples
m = 100

In [968]:
import numpy as np
import pandas as pd
from math import *
import matplotlib.pyplot as plt
from sklearn.preprocessing import Normalizer
from sklearn.cluster import KMeans

## Kmeans

In [969]:
class Clustering:
    def __init__(self, path='accounts_style.csv' ):
        self.path = path
        self.data = self.__preprecessing(path)
        self.data = self.__normalize_based_on_values([2, 2, 1.5, 1.25, 1.75])

    def row_processing(self, data):
        #print(self.data)
        #select special part of the dataframe
        data = data.iloc[ : ,2:]

        #spilit data and add new culomns
        data[['Age1', 'Age2', 'Age3']] = data["Age"].str.split(",", n=2, expand=True)
        data[['Color1', 'Color2', 'Color3']] = data["Color"].str.split(",", n=2, expand=True)
        data[['Pattern1', 'Pattern2', 'Pattern3']] = data["Pattern"].str.split(",", n=2, expand=True)
        data[['Size1', 'Size2', 'Size3']] = data["Size"].str.split(",", n=2, expand=True)
        data[['Formal1', 'Formal2', 'Formal3']] = data["Formal"].str.split(",", n=2, expand=True)

        #drop unusage columns
        data.drop(columns =['Age', 'Color', 'Pattern', 'Size', 'Formal'], inplace = True)

        #convert type from str to float64
        data = data.astype('float64')

        #calculate the average of each row specialy
        data['Age_avg'] = self.__special_mean(data[['Age1', 'Age2', 'Age3']].values,20)
        data['Color-avg'] = self.__special_mean(data[['Color1', 'Color2', 'Color3']].values,20)
        data['Pattern_avg'] = self.__special_mean(data[['Pattern1', 'Pattern2', 'Pattern3']].values,20)
        data['Size-avg'] = self.__special_mean(data[['Size1', 'Size2', 'Size3']].values,20)
        data['Formal_avg'] = self.__special_mean(data[['Formal1', 'Formal2', 'Formal3']].values,20)
        
        #drop unusage columns
        data.drop(columns =['Age1', 'Age2', 'Age3', 'Color1', 'Color2', 'Color3', 'Pattern1',
         'Pattern2', 'Pattern3', 'Size1', 'Size2', 'Size3', 'Formal1', 'Formal2', 'Formal3'], inplace = True)
         
        ind = data.columns
        data = self.preprocess.transform(data)
        print(data)
        data = pd.DataFrame(data, columns=['Age_avg', 'Color-avg', 'Pattern_avg', 'Size-avg', 'Formal_avg'])
        data = (data - 0.5) * 2#            Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg
        data = data * self.values
        return data



    def getData(self):
        return self.data


    def fit_predict(self, n_clusters=6):
        kmeans = KMeans(n_clusters = n_clusters, init = 'k-means++', random_state = 42)
        self.kmeans = kmeans
        print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$asdffffffffffffffffffffffffffff$$$$$$$$$$$$$$$$$$$$$")
        print(self.data)
        return kmeans.fit_predict(self.data)


    def cluster_centers(self):
        return self.kmeans.cluster_centers_


    def predict(self, input):
        return self.kmeans.predict(input)

    
    def __preprecessing(self, path):
        #select special part of the dataframe
        data = pd.read_csv(path)
        data = data.iloc[ : ,2:]

        #spilit data and add new culomns
        data[['Age1', 'Age2', 'Age3']] = data["Age"].str.split(",", n=2, expand=True)
        data[['Color1', 'Color2', 'Color3']] = data["Color"].str.split(",", n=2, expand=True)
        data[['Pattern1', 'Pattern2', 'Pattern3']] = data["Pattern"].str.split(",", n=2, expand=True)
        data[['Size1', 'Size2', 'Size3']] = data["Size"].str.split(",", n=2, expand=True)
        data[['Formal1', 'Formal2', 'Formal3']] = data["Formal"].str.split(",", n=2, expand=True)

        #drop unusage columns
        data.drop(columns =['Age', 'Color', 'Pattern', 'Size', 'Formal'], inplace = True)

        #convert type from str to float64
        data = data.astype('float64')

        #calculate the average of each row specialy
        data['Age_avg'] = self.__special_mean(data[['Age1', 'Age2', 'Age3']].values,20)
        data['Color-avg'] = self.__special_mean(data[['Color1', 'Color2', 'Color3']].values,20)
        data['Pattern_avg'] = self.__special_mean(data[['Pattern1', 'Pattern2', 'Pattern3']].values,20)
        data['Size-avg'] = self.__special_mean(data[['Size1', 'Size2', 'Size3']].values,20)
        data['Formal_avg'] = self.__special_mean(data[['Formal1', 'Formal2', 'Formal3']].values,20)

        #drop unusage columns
        data.drop(columns =['Age1', 'Age2', 'Age3', 'Color1', 'Color2', 'Color3', 'Pattern1',
         'Pattern2', 'Pattern3', 'Size1', 'Size2', 'Size3', 'Formal1', 'Formal2', 'Formal3'], inplace = True)

        return data



    def __normalize_based_on_values(self, values):
        #normalize data from 0 to 1
        self.values = values
        preprocess = Normalizer().fit(self.data)
        inputData = preprocess.transform(self.data)
        normalized_data = pd.DataFrame(inputData, columns=self.data.columns)
        self.preprocess = preprocess

        #put it in -1 to +1
        normalized_data = (normalized_data - 0.5) * 2

        #change the period for each component to change the influence
        normalized_data = normalized_data * values
        return normalized_data


    def __special_mean(self, selectedClothes, anomaly):
        # we have to ignore anomaly values in each component to have accessed the real mean value
        meanVector = []
        for i in range(np.shape(selectedClothes)[0]):
            componentSum = 0
            count = 0
            for j in range(np.shape(selectedClothes)[1]):
                if(selectedClothes[i][j] != anomaly):
                    componentSum += selectedClothes[i][j]
                    count += 1
            meanVector.append(componentSum/count)

        return meanVector




## recommend

In [970]:
class RecommendationSystem:
    
    def __init__(self, allClothes):
        self.allClothes = allClothes
        self.clustering = Clustering(path='accounts_style.csv')
        self.answers = self.clustering.fit_predict(n_clusters=6)
        self.preparedData = self.clustering.getData()
        self.preparedData.insert(0, 'Id', range(1,401))
        self.preparedDataWithAnswers = self.preparedData
        self.preparedDataWithAnswers['Answers'] = self.answers


        
    def get_prepared_data(self):
        return self.preparedData

    def get_prepared_data_with_anwers(self):
        return self.preparedDataWithAnswers

    def recommend_based_on_questions(self, values, customer_feature1, customer_feature2, customer_feature3, customer_feature4, k1 = 4, k2=1, k3=1, k4=1):
    
        #k nearest neighbor
        k_indices1 = self.__one_recommend(customer_feature1, values, k1)
        k_indices2 = self.__one_recommend(customer_feature2, values, k2)
        k_indices3 = self.__one_recommend(customer_feature3, values, k3)
        k_indices4 = self.__one_recommend(customer_feature4, values, k4)
                
        # merge and unigue indices(union)
        k_indices = np.append(k_indices1, np.append(k_indices2, np.append(k_indices3, k_indices4)))
        
        # return the selected style indices 
        return k_indices


    def recommend_based_on_clothes(self, selectedClothes, values, anomaly = 20, k=5):
        
        #asume average of the each component for the as the customer vector of self.__oneRecommend little diffrent with the ordinary averages
        average_of_multi_tags = self.__special_mean(selectedClothes, anomaly)
        k_indeces = self.__one_recommend(average_of_multi_tags, values, k)
        return k_indeces


    def recommend_based_on_cluster(self, cluster_taste, k=30):
        tasteSum = sum(cluster_taste)
        selected_indices = []
        for i in range(len(cluster_taste)):
            selected_indices.append(self.__k_recommend_recommend_based_on_cluster(i, math.ceil(k*cluster_taste[i]/tasteSum)))
        selected_indices = self.__flatten(selected_indices)
        random.shuffle(selected_indices)    
        return selected_indices



    def add_item(self, clothes, id):
        clothes = pd.DataFrame(clothes, columns=['Id','Url','Age','Color','Pattern','Size','Formal'])
        clothes = self.clustering.row_processing(clothes)
        answer = self.clustering.predict(clothes)
        clothes['Answers'] = answer
        clothes.insert(0, 'Id', id)
        self.preparedData.append(clothes)
        self.preparedDataWithAnswers.append(clothes)
        return 1


    def __k_recommend_recommend_based_on_cluster(self, index, k):
        indices = self.preparedDataWithAnswers[self.preparedDataWithAnswers['Answers'] == index].index
        rndIndices = random.choices(indices, k=2*k)
        random.shuffle(rndIndices)
        return rndIndices[:k]


    def __one_recommend(self, customer, values, k):
        # compute distances by one of the distance(distance_1, distance_2, ...) functions
        distances = np.array([self.__similarity2(customer, f, values) for f in self.allClothes])
        
        # return k nearest style indices
        return np.argsort(distances)[: k]


    def __flatten(self, t):
        return [item for sublist in t for item in sublist]


    def normal_recommend_question2(self):
        question2Indices = []
        for i in range(0,6):
            oneClusterIndices = self.preparedDataWithAnswers[self.preparedDataWithAnswers['Answers'] == i].index
            question2Indices.append(random.choice(oneClusterIndices))
        return question2Indices
    

    def update_cluster_taste(self, prev_cluster_taste, comment, clothesInd, alpha = 0.3 ):
        #find the class number of clothes
        #clusterNumber = self.which_cluster(clothesInd)
        clusterNumber = self.preparedDataWithAnswers['Answers'][clothesInd - 1]
        
        #calculate the new replacement for selected cluster with weighted average
        weightedAverage = np.average([prev_cluster_taste[clusterNumber], comment], weights=[1,alpha])

        #update prev_Cluster_taste 
        prev_cluster_taste[clusterNumber] = weightedAverage
        return prev_cluster_taste


    def get_data(self):
        return self.preparedData


    def favorite_items(inputmatrix):
        items = pd.DataFrame(inputmatrix, columns=['id', 'average', 'count'])
        items['average'] = 0.5 *(2*items['average']).apply(np.ceil)
        items.sort_values(['average', 'count'], inplace=True, ascending=False)
        return items.values


    def which_cluster(ClothesInd):
        return 1


    def __similarity1(self, customer, clothes, values):
        lowestMines = self.__lowest_mines(customer, clothes)      
        return np.sum(values * np.abs(lowestMines))
    
    
    def __similarity2(self, customer, clothes, values):
        lowestMines = self.__lowest_mines(customer, clothes)      
        return np.sqrt(np.sum(values*((lowestMines) ** 2 )))


    def __lowest_mines(self, customer, clothes):
        bestClothes = []
        tmpArray1 = []
        for i in range(len(customer)):
            for j in range(np.shape(clothes)[1]):
                tmpArray1.append(abs((customer[i] - clothes[i][j])))
            bestClothes.append(min(tmpArray1))  
            tmpArray1 = []
        return np.array(bestClothes)


    def __special_mean(self, selectedClothes, anomaly):
        # we have to ignore anomaly values in each component to have access the real mean value
        meanVector = []
        for i in range(np.shape(selectedClothes)[0]):
            componentSum = 0
            count = 0
            for j in range(np.shape(selectedClothes)[1]):
                if(selectedClothes[i][j] != anomaly):
                    componentSum += selectedClothes[i][j]
                    count += 1
            meanVector.append(componentSum/count)

        return meanVector
            

### 1.Test of recommend_based_on_questions function 
---
creating random data and check the answers of recommend_based_on_questions function, subfunctions.
its subfuctions including:
- __similarity2
- __lowest_mines
- __one_recommend



In [971]:
import random 

In [972]:
#create random clothes tags
my_list = [0, 1, 2, 3, 4]
clothes = np.zeros((m, n, 3))
for i in range(m):
    for j in range(n):
        for k in range(3):
            clothes[i, j, k] = random.choice(my_list)
    
print(clothes[:2])

[[[0. 2. 2.]
  [0. 0. 2.]
  [1. 2. 1.]
  [3. 3. 2.]
  [1. 3. 3.]]

 [[4. 4. 2.]
  [3. 1. 2.]
  [0. 3. 3.]
  [1. 0. 1.]
  [2. 2. 1.]]]


In [973]:
#create random personal tags
customer1 = np.array([random.choice(my_list) for j in range(n)])

#create 3 random selected style tags
customer2 = np.array([random.choice(my_list) for j in range(n)])
customer3 = np.array([random.choice(my_list) for j in range(n)])
customer4 = np.array([random.choice(my_list) for j in range(n)])
print(customer1, customer2, customer3, customer4)

[2 1 3 1 4] [2 4 2 4 1] [0 3 4 4 3] [0 1 0 0 3]


In [974]:
recommendationSystem = RecommendationSystem(clothes)

distances_indices = recommendationSystem.recommend_based_on_questions([1,1,1,1,1], customer1, customer2, customer3, customer4)

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$asdffffffffffffffffffffffffffff$$$$$$$$$$$$$$$$$$$$$
      Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg
0   -0.351673   0.747211    -1.087918 -0.219796   -0.307714
1   -0.045289   0.443389    -1.133492 -0.333729   -0.039628
2   -0.845299   0.886751    -1.066987 -0.167468   -0.234456
3   -0.780011   1.049971    -1.042504 -0.487507   -0.148765
4   -0.718975   0.562050    -1.019616 -0.049039   -0.068654
..        ...        ...          ...       ...         ...
395 -0.166603  -0.166603    -0.949981 -0.333302    0.495911
396 -0.592805   0.814390    -0.233524 -0.546402   -0.518704
397 -0.492443   0.713602    -0.143199 -0.307777   -0.958533
398 -0.158851  -0.158851     0.157034 -0.329425   -0.461196
399 -0.623143   0.753714    -0.260829 -0.389465   -0.545250

[400 rows x 5 columns]


In [975]:
print(customer1)
print(clothes[distances_indices])
type(distances_indices)

[2 1 3 1 4]
[[[0. 3. 2.]
  [1. 0. 4.]
  [0. 3. 4.]
  [3. 1. 2.]
  [1. 2. 4.]]

 [[0. 0. 2.]
  [1. 3. 0.]
  [3. 2. 2.]
  [1. 3. 2.]
  [0. 4. 2.]]

 [[4. 0. 2.]
  [4. 1. 4.]
  [0. 3. 3.]
  [0. 4. 1.]
  [0. 4. 2.]]

 [[2. 3. 1.]
  [1. 2. 2.]
  [2. 3. 0.]
  [0. 4. 1.]
  [4. 4. 2.]]

 [[0. 0. 2.]
  [4. 3. 3.]
  [4. 2. 2.]
  [4. 2. 4.]
  [0. 2. 1.]]

 [[0. 4. 1.]
  [2. 3. 2.]
  [4. 4. 1.]
  [3. 4. 0.]
  [3. 2. 1.]]

 [[1. 1. 0.]
  [2. 4. 1.]
  [3. 4. 0.]
  [0. 0. 0.]
  [1. 4. 3.]]]


numpy.ndarray

### 2.Test of update_cluster_taste function 
---
creating random data and check the answers of update_cluster_taste function, subfunctions.
its subfuctions including:
- __which_cluster

In [976]:
#__wich_cluster always return 1 untill clustering implementation
clusterTaste = [5, 5, 5, 5, 5]
recommendationSystem.update_cluster_taste(prev_cluster_taste=clusterTaste, comment=1, clothesInd=145)

[5, 5, 5, 5, 4.076923076923077]

### 3.Test of recommend_based_on_clothes function 
---
creating random data and check the answers of recommend_based_on_clothes function, subfunctions.
its subfuctions including:
- __special_mean
- __one_recommend

In [977]:
clothesTest = [[1,2,10], [1,10,10], [3,4,10], [1,2,3], [2,3,4]]
indecesTest3 = recommendationSystem.recommend_based_on_clothes(clothesTest, values=[1,1,1,1,1], anomaly=10 )
clothes[indecesTest3]

array([[[1., 3., 0.],
        [4., 1., 2.],
        [4., 0., 4.],
        [1., 4., 2.],
        [0., 1., 3.]],

       [[0., 3., 2.],
        [1., 1., 4.],
        [0., 3., 0.],
        [2., 3., 3.],
        [4., 1., 3.]],

       [[1., 3., 4.],
        [2., 4., 1.],
        [4., 4., 3.],
        [2., 2., 1.],
        [1., 1., 3.]],

       [[3., 2., 0.],
        [1., 4., 0.],
        [3., 4., 3.],
        [2., 2., 3.],
        [3., 0., 3.]],

       [[0., 4., 1.],
        [1., 3., 0.],
        [3., 3., 3.],
        [2., 4., 4.],
        [4., 2., 3.]]])

## Checked data

In [978]:
preparedData = recommendationSystem.get_prepared_data_with_anwers()

In [979]:
preparedData

Id   Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg  Answers
0      1 -0.351673   0.747211    -1.087918 -0.219796   -0.307714        4
1      2 -0.045289   0.443389    -1.133492 -0.333729   -0.039628        4
2      3 -0.845299   0.886751    -1.066987 -0.167468   -0.234456        0
3      4 -0.780011   1.049971    -1.042504 -0.487507   -0.148765        0
4      5 -0.718975   0.562050    -1.019616 -0.049039   -0.068654        4
..   ...       ...        ...          ...       ...         ...      ...
395  396 -0.166603  -0.166603    -0.949981 -0.333302    0.495911        4
396  397 -0.592805   0.814390    -0.233524 -0.546402   -0.518704        5
397  398 -0.492443   0.713602    -0.143199 -0.307777   -0.958533        5
398  399 -0.158851  -0.158851     0.157034 -0.329425   -0.461196        2
399  400 -0.623143   0.753714    -0.260829 -0.389465   -0.545250        5

[400 rows x 7 columns]

In [980]:
preparedData.to_csv('sample.csv')


## recommend_based_on_cluster

In [981]:
recommendationSystem.recommend_based_on_cluster([1,5,2,1,1,2], k=30)


[99,
 49,
 166,
 6,
 330,
 180,
 286,
 390,
 369,
 369,
 297,
 48,
 176,
 138,
 0,
 375,
 218,
 288,
 325,
 33,
 70,
 267,
 52,
 380,
 131,
 88,
 311,
 180,
 267,
 204,
 328,
 362]

## test of faourite_items

In [982]:
a =[[1,4.1,4],[2,3.9,4],[3,2.3,5],[5,4.4,2]]
print(a)

RecommendationSystem.favorite_items(a)

[[1, 4.1, 4], [2, 3.9, 4], [3, 2.3, 5], [5, 4.4, 2]]


array([[1. , 4.5, 4. ],
       [5. , 4.5, 2. ],
       [2. , 4. , 4. ],
       [3. , 2.5, 5. ]])

In [983]:
recommendationSystem.get_data()

Id   Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg  Answers
0      1 -0.351673   0.747211    -1.087918 -0.219796   -0.307714        4
1      2 -0.045289   0.443389    -1.133492 -0.333729   -0.039628        4
2      3 -0.845299   0.886751    -1.066987 -0.167468   -0.234456        0
3      4 -0.780011   1.049971    -1.042504 -0.487507   -0.148765        0
4      5 -0.718975   0.562050    -1.019616 -0.049039   -0.068654        4
..   ...       ...        ...          ...       ...         ...      ...
395  396 -0.166603  -0.166603    -0.949981 -0.333302    0.495911        4
396  397 -0.592805   0.814390    -0.233524 -0.546402   -0.518704        5
397  398 -0.492443   0.713602    -0.143199 -0.307777   -0.958533        5
398  399 -0.158851  -0.158851     0.157034 -0.329425   -0.461196        2
399  400 -0.623143   0.753714    -0.260829 -0.389465   -0.545250        5

[400 rows x 7 columns]

In [984]:
recommendationSystem.get_data().append(a)

0    1    2   Age_avg  Answers  Color-avg  Formal_avg     Id  \
0    NaN  NaN  NaN -0.351673      4.0   0.747211   -0.307714    1.0   
1    NaN  NaN  NaN -0.045289      4.0   0.443389   -0.039628    2.0   
2    NaN  NaN  NaN -0.845299      0.0   0.886751   -0.234456    3.0   
3    NaN  NaN  NaN -0.780011      0.0   1.049971   -0.148765    4.0   
4    NaN  NaN  NaN -0.718975      4.0   0.562050   -0.068654    5.0   
..   ...  ...  ...       ...      ...        ...         ...    ...   
399  NaN  NaN  NaN -0.623143      5.0   0.753714   -0.545250  400.0   
0    1.0  4.1  4.0       NaN      NaN        NaN         NaN    NaN   
1    2.0  3.9  4.0       NaN      NaN        NaN         NaN    NaN   
2    3.0  2.3  5.0       NaN      NaN        NaN         NaN    NaN   
3    5.0  4.4  2.0       NaN      NaN        NaN         NaN    NaN   

     Pattern_avg  Size-avg  
0      -1.087918 -0.219796  
1      -1.133492 -0.333729  
2      -1.066987 -0.167468  
3      -1.042504 -0.487507  
4      -1.019616 -0.049039  
..           ...       ...  
399    -0.260829 -0.389465  
0            NaN       NaN  
1            NaN       NaN  
2            NaN       NaN  
3            NaN       NaN  

[404 rows x 10 columns]

In [985]:
recommendationSystem.get_data()


Id   Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg  Answers
0      1 -0.351673   0.747211    -1.087918 -0.219796   -0.307714        4
1      2 -0.045289   0.443389    -1.133492 -0.333729   -0.039628        4
2      3 -0.845299   0.886751    -1.066987 -0.167468   -0.234456        0
3      4 -0.780011   1.049971    -1.042504 -0.487507   -0.148765        0
4      5 -0.718975   0.562050    -1.019616 -0.049039   -0.068654        4
..   ...       ...        ...          ...       ...         ...      ...
395  396 -0.166603  -0.166603    -0.949981 -0.333302    0.495911        4
396  397 -0.592805   0.814390    -0.233524 -0.546402   -0.518704        5
397  398 -0.492443   0.713602    -0.143199 -0.307777   -0.958533        5
398  399 -0.158851  -0.158851     0.157034 -0.329425   -0.461196        2
399  400 -0.623143   0.753714    -0.260829 -0.389465   -0.545250        5

[400 rows x 7 columns]

In [986]:
recommendationSystem.get_prepared_data()

Id   Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg  Answers
0      1 -0.351673   0.747211    -1.087918 -0.219796   -0.307714        4
1      2 -0.045289   0.443389    -1.133492 -0.333729   -0.039628        4
2      3 -0.845299   0.886751    -1.066987 -0.167468   -0.234456        0
3      4 -0.780011   1.049971    -1.042504 -0.487507   -0.148765        0
4      5 -0.718975   0.562050    -1.019616 -0.049039   -0.068654        4
..   ...       ...        ...          ...       ...         ...      ...
395  396 -0.166603  -0.166603    -0.949981 -0.333302    0.495911        4
396  397 -0.592805   0.814390    -0.233524 -0.546402   -0.518704        5
397  398 -0.492443   0.713602    -0.143199 -0.307777   -0.958533        5
398  399 -0.158851  -0.158851     0.157034 -0.329425   -0.461196        2
399  400 -0.623143   0.753714    -0.260829 -0.389465   -0.545250        5

[400 rows x 7 columns]

In [987]:
recommendationSystem.get_prepared_data_with_anwers()

Id   Age_avg  Color-avg  Pattern_avg  Size-avg  Formal_avg  Answers
0      1 -0.351673   0.747211    -1.087918 -0.219796   -0.307714        4
1      2 -0.045289   0.443389    -1.133492 -0.333729   -0.039628        4
2      3 -0.845299   0.886751    -1.066987 -0.167468   -0.234456        0
3      4 -0.780011   1.049971    -1.042504 -0.487507   -0.148765        0
4      5 -0.718975   0.562050    -1.019616 -0.049039   -0.068654        4
..   ...       ...        ...          ...       ...         ...      ...
395  396 -0.166603  -0.166603    -0.949981 -0.333302    0.495911        4
396  397 -0.592805   0.814390    -0.233524 -0.546402   -0.518704        5
397  398 -0.492443   0.713602    -0.143199 -0.307777   -0.958533        5
398  399 -0.158851  -0.158851     0.157034 -0.329425   -0.461196        2
399  400 -0.623143   0.753714    -0.260829 -0.389465   -0.545250        5

[400 rows x 7 columns]